version: "3"

services:
  trueque_api:
    build: .
    container_name: trueque-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    networks:
      - trueque-network

networks:
  trueque-network:
    external: true